environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "14"
    # TODO: Uncomment when node15 is available.
    # https://github.com/FormidableLabs/trace-pkg/issues/6
    # - nodejs_version: "15"

branches:
  only:
    - main

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"

# Post-install test scripts.
test_script:
  - node --version
  - yarn --version
  - node bin/trace-pkg.js -v
  - node bin/trace-pkg.js -h
  - yarn check-ci

# Don't actually build.
build: off

matrix:
  fast_finish: true
